### PR TITLE
update project dependencies

### PR DESCRIPTION
**Pull request by minghinmatthewlam**
How this works:
- Since project requires python 3.10, updated in `pyproject.toml`
- Updates mypy version to `0.982` minimum to avoid issue here https://github.com/numpy/numpy/issues/22412
```
pypoetry/virtualenvs/hyperliquid-python-sdk-y6lYbV5e-py3.10/lib/python3.10/site-packages/pkg_resources-stubs/__init__.pyi:329:79: error: Positional-only
parameters are only supported in Python 3.8 and greater  [syntax]
```

### CODE REVIEW

**Review by traderben — CHANGES_REQUESTED** [review]
We cannot drop support for python 3.8 and 3.9. Many users still use those versions

**Comment by minghinmatthewlam** [comment]
@traderben I removed it, but if the latest commits require `python 3.10` to build, why keep it as part of `pyproject.toml` instead of having people upgrade versions? Seems strange to allow a version that is not compatible with building the repo.

**Comment by traderben** [comment]
> @traderben I removed it, but if the latest commits require `python 3.10` to build, why keep it as part of `pyproject.toml` instead of having people upgrade versions? Seems strange to allow a version that is not compatible with building the repo.

Which commits require python 3.10? Apologies if something slipped through testing. The project is set up to allow users to use 3.8+, but development requires 3.10

**Comment by minghinmatthewlam** [comment]
> > @traderben I removed it, but if the latest commits require `python 3.10` to build, why keep it as part of `pyproject.toml` instead of having people upgrade versions? Seems strange to allow a version that is not compatible with building the repo.
> 
> Which commits require python 3.10? Apologies if something slipped through testing. The project is set up to allow users to use 3.8+, but development requires 3.10

oh ye my bad that's only for developers looking to build this repo, but there's still people using the sdk with older versions, disregard.

**Comment by traderben** [comment]
I'm unable to install with python 3.8:
```
AttributeError: cython_sources


  at ~/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/poetry/installation/chef.py:152 in _prepare
      148│
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│
      151│             if error is not None:
    → 152│                 raise error from None
      153│
      154│             return path
      155│
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pyyaml (6.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pyyaml (==6.0)"'.
```
Is supporting development with other versions of python important for you? I'm going to approve the other PR that bumps the mypy dependency without changing the supported development version of python

**Comment by minghinmatthewlam** [comment]
closign 0.981 was merged

**Pull request closed without merging**
